name: Build

on:
    pull_request:

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2

            -   name: Validate composer.json
                run: composer validate --strict

            -   name: Composer Audit
                run: composer audit

            -   name: Install dependencies
                run: composer install --no-interaction --prefer-dist

            -   name: Create static image
                run: ./build-static.sh
                working-directory: build

            -   name: Build executable phar
                run: php build.php
                working-directory: build
